### ISSUE TITLE
Can some one give me the code to check the stock on the account gen bot and tell me where to put it?

### ISSUE THREAD

**Issue by bluergh420** [silvanohirtie/account-generator#10]
Just looking for code to check the stock on the account generator bot. So some one can type something like /stock and it will read and show how many accounts are on the txt file. I'm fairly new to this. So bare with me.

**Comment by MyFace40** [comment]
Hi, i am relatively new too.
So,I read some guiides and found this
var fs9 = require('fs');
hfilePath = process.argv[2];
hfileBuffer = fs9.readFileSync('./ACC/type.txt');
hto_string = hfileBuffer.toString();
hsplit_lines = hto_string.split("\n");
var type = (hsplit_lines.length);

**Comment by alexakaka** [comment]
there is alredy a stock command
