### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by ppsquizzes** [silvanohirtie/account-generator#16]
Where does the token go

**Comment by gitpodmine** [comment]
open index.js using any text editor and at the complet bottom u will find (TOKEN)
just replace that with ("your bot token") and it should work after u save it

**Comment by JavaScriptOP** [comment]
> open index.js using any text editor and at the complet bottom u will find (TOKEN)
> just replace that with ("your bot token") and it should work after u save it. u must keep the quote for it to work

or, you can add it to the config and make it config.token, but that works too i guess

**Comment by silvanohirtie** [comment]
> 
> 
> > open index.js using any text editor and at the complet bottom u will find (TOKEN)
> > just replace that with ("your bot token") and it should work after u save it. u must keep the quote for it to work
> 
> or, you can add it to the config and make it config.token, but that works too i guess

that would be a little useless and dangerous since the config file is editable through a command.
@ppsquizzes just replace the token on last line of index.js

**Comment by JavaScriptOP** [comment]
> > > open index.js using any text editor and at the complet bottom u will find (TOKEN)
> > > just replace that with ("your bot token") and it should work after u save it. u must keep the quote for it to work
> > 
> > 
> > or, you can add it to the config and make it config.token, but that works too i guess
> 
> that would be a little useless and dangerous since the config file is editable through a command.
> @ppsquizzes just replace the token on last line of index.js

how? unless you made a command to show and edit the config, NO ONE EXCEPT YOU (the person who has access to the bots files) can use it
