### ISSUE TITLE
bulk add doesn’t seem to work

### ISSUE THREAD

**Issue by gitpodmine** [silvanohirtie/account-generator#17]
i don’t if i am doing it wrong but i cannot add multiple account at the same time could u help me a little on that . i even tried by sending txt file but i get an error about slice(0) or something

**Comment by JavaScriptOP** [comment]
> i don’t if i am doing it wrong but i cannot add multiple account at the same time could u help me a little on that . i even tried by sending txt file but i get an error about slice(0) or something

it is not part of the bot _YET,_ i recommend learning javascript.

**Comment by silvanohirtie** [comment]
right now you can add just 1 account by command.
In V4 there will be a way to do bulk add accounts.
