### ISSUE TITLE
ADD A NEW FEATURE

### ISSUE THREAD

**Issue by KAPILPAJI** [silvanohirtie/account-generator#21]
PLEASE ADD A NEW FEATURE LIKE FROM WHICH WE CAN SETUP SOME SPECIFIC CHANNEL AND SOME SPECIFIC ROLES TO ONLY GEN ANYTHING

**Comment by silvanohirtie** [comment]
that will come in a next update

Il giorno mer 25 nov 2020 alle ore 18:09 KAPILPAJI <notifications@github.com>
ha scritto:

**Comment by KAPILPAJI** [comment]
When will next update come

**Comment by silvanohirtie** [comment]
I do not have a lot of time to spend on this project, I think maybe
December 2020 / January 2021

Il giorno gio 26 nov 2020 alle ore 12:55 KAPILPAJI <notifications@github.com>
ha scritto:
