### ISSUE TITLE
Accounts Stock disappeared automatically after 24 hours

### ISSUE THREAD

**Issue by Cryptojegar** [silvanohirtie/account-generator#22]
I Added some Account from my services but after 24 hours my stock become empty, plz help! Thanks.

**Comment by silvanohirtie** [comment]
that makes no sense, the code does not touch the stock files if not
triggered.

Il giorno lun 30 nov 2020 alle ore 14:32 Cryptojegar <
notifications@github.com> ha scritto:

**Comment by F1R3L1GHT** [comment]
are u using heroku :joy:
