### ISSUE TITLE
Please, help (heroku)

### ISSUE THREAD

**Issue by Filipery** [silvanohirtie/account-generator#3]
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.18.1...
       Using default npm version: 6.14.5
       
-----> Installing dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules
       
       > nodemon@2.0.3 postinstall /tmp/build_d366abc64604280056cbf5ac5815c7a4/node_modules/nodemon
       > node bin/postinstall || exit 0
       
       Love nodemon? You can now support the project via the open collective:
        > https://opencollective.com/nodemon/donate
       
       
       > sqlite3@4.1.1 install /tmp/build_d366abc64604280056cbf5ac5815c7a4/node_modules/sqlite3
       > node-pre-gyp install --fallback-to-build
       
       sh: 1: node-pre-gyp: Permission denied
       npm ERR! code ELIFECYCLE
       npm ERR! errno 126
       npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
       npm ERR! Exit status 126
       npm ERR! 
       npm ERR! Failed at the sqlite3@4.1.1 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.s3QZf/_logs/2020-06-29T19_27_11_181Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - node_modules checked into source control
         https://blog.heroku.com/node-habits-2016#9-only-git-the-important-bits
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

Package.json:

{
  "name": "account-generator",
  "version": "1.0.0",
  "description": "A discord bot you can use to give accounts to your server's members",
  "main": "index.js",
  "engines": {
    "node": "13.3.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/silvanohirtie/account-generator.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/silvanohirtie/account-generator/issues"
  },
  "homepage": "https://github.com/silvanohirtie/account-generator#readme",
  "dependencies": {
    "async": "^3.1.0",
    "discord.js": "^11.5.1",
    "express": "^4.17.1",
    "firstline": "^2.0.2",
    "glob": "^7.1.6",
    "line-reader": "^0.4.0",
    "node-pre-gyp": "^0.15.0"
  }
}

**Comment by ClearlyElevated** [comment]
I see two errors in the package file. There isn’t a startup command and the brackets at the bottom should have an additional indent on the last one

**Comment by silvanohirtie** [comment]
@ClearlyElevated it does not need a start command, as I see it’s an heroku problem
