### ISSUE TITLE
Stock Command

### ISSUE THREAD

**Issue by NotttCn** [silvanohirtie/account-generator#30]
Hello, so I wanted to change the stock command https://cdn.discordapp.com/attachments/814830529785495562/814831509046558720/unknown.png
![image](https://user-images.githubusercontent.com/79747855/109385198-2a82a580-7903-11eb-91d9-159e9ff66aec.png)
 this's what it looks like but the problem is whenever I type /stock it just spams and it's annoying I want it to look advanced like this for example: 
![image](https://user-images.githubusercontent.com/79747855/109385195-25255b00-7903-11eb-97a1-39b69ea496c6.png)

But I don't know how am not a JS expert can you please help?

**Comment by silvanohirtie** [comment]
it will come in the next version, not planned for now.
