### ISSUE TITLE
Issue with the bot

### ISSUE THREAD

**Issue by ZaH151** [silvanohirtie/account-generator#33]
I searched and all i found is that the problem can be teh code so i want to know if i did someting wrong.

[index.zip](https://github.com/silvanohirtie/account-generator/files/6143260/index.zip)
Sorry i needed to use the zip, but if someone want JPGs i will put it to the answer, thanks

**Comment by H-Killer** [comment]
what is your problem ?

**Comment by H-Killer** [comment]
what is your problem?

**Comment by ZaH151** [comment]
The bot is not online i put the index.js there cause i don't know if i did something wrong with it

**Comment by H-Killer** [comment]
You need to run the bot to be online (Open terminal then write `node .` ) and if you need it to stay 7/24 you need to host it.
If a problem appeared, feel free to send a screenshot to me on discord **killer#0005**

**Comment by ZaH151** [comment]
ill do when i can, thank you

**Comment by H-Killer** [comment]
Welcome

**Comment by ClearlyElevated** [comment]
> The bot is not online i put the index.js there cause i don't know if i did something wrong with it
> 
> 

Maybe don't edit things if you don't know how to code? Revert the file to it's original state
