### ISSUE TITLE
error

### ISSUE THREAD

**Issue by EaZyWaRe** [silvanohirtie/account-generator#35]
ReferenceError: ODIyMTM3ODA0OTMwODA5OTQ2 is not defined
    at Object.<anonymous> (C:\Users\grueg\Desktop\account-generator-master\index.js:236:11)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1092:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:972:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:813:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m

when i starting

**Comment by H-Killer** [comment]
You need to put your token between ""

`"Your_Toke"`
