### ISSUE TITLE
Setting the bot up..

### ISSUE THREAD

**Issue by cliphd** [silvanohirtie/account-generator#40]
How do i go about setting the bot up? what do i use? Also, can I import other things like codes and links?

**Comment by ClearlyElevated** [comment]
You give no detail as to codes and links. And if you mean add your own links that's copyright infringement

**Comment by cliphd** [comment]
No, I mean instead of accounts can I have it send links, like Discord nitro and codes like V-bucks, Robux, Amazon, etc.
