### ISSUE TITLE
I want a stock command

### ISSUE THREAD

**Issue by ICUBICI** [silvanohirtie/account-generator#6]
So I Saw There Wasnt A Stock Command Like $stock and it shows the amount of stock in each file or something if anyone knows one please feel free to send to code to me

**Comment by silvanohirtie** [comment]
make it that when a user type $stock, the bot searches in the folder all
the txt files and make it send their names

Il giorno gio 23 lug 2020 alle 04:34 ICUBICI <notifications@github.com> ha
scritto:

**Comment by bluergh420** [comment]
How @silvanohirtie
